using System.Text.Json.Serialization;
using CounterStrikeSharp.API.Core;

namespace InspectGive;

/// <summary>
/// Plugin config, auto-generated by CounterStrikeSharp at
/// <c>configs/plugins/InspectGive/InspectGive.json</c> on first load. hooks/pre.sh
/// templates this from the same WP_DB_* env vars WeaponPaints uses, so the two
/// plugins always point at the same MariaDB.
/// </summary>
public sealed class InspectGiveConfig : BasePluginConfig
{
    [JsonPropertyName("DatabaseHost")] public string DatabaseHost { get; set; } = "mariadb";
    [JsonPropertyName("DatabasePort")] public uint DatabasePort { get; set; } = 3306;
    [JsonPropertyName("DatabaseName")] public string DatabaseName { get; set; } = "weaponpaints";
    [JsonPropertyName("DatabaseUser")] public string DatabaseUser { get; set; } = "weaponpaints";
    [JsonPropertyName("DatabasePassword")] public string DatabasePassword { get; set; } = "";

    /// <summary>Apply to both T (2) and CT (3) loadouts so the skin shows on either side.</summary>
    [JsonPropertyName("ApplyToBothTeams")] public bool ApplyToBothTeams { get; set; } = true;

    /// <summary>The chat prefix that triggers an inspect: the console command word
    /// copied from cs2inspects.com, so you can paste the whole line into chat. Note CS2's
    /// chat box truncates long lines, so full blobs usually need <see cref="Command"/>.</summary>
    [JsonPropertyName("ChatTriggerPrefix")] public string ChatTriggerPrefix { get; set; } = "csgo_econ_action_preview";

    /// <summary>Console command for pasting an inspect blob from the in-game console (`~`).
    /// The console accepts ~512 chars vs. the chat box's much shorter cap, so this is the
    /// reliable path for full-length blobs. Requires the full
    /// <c>inspect csgo_econ_action_preview &lt;hex&gt;</c> line.</summary>
    [JsonPropertyName("Command")] public string Command { get; set; } = "inspect";
}
